# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AppTorcedorNE10' do

pod 'AFNetworking', '2.5.4'
pod 'MBProgressHUD', '0.9.1'
pod 'CCBottomRefreshControl'
pod  'mopub-ios-sdk','3.9.0'
pod "FBSDKCoreKit"
pod "FBSDKLoginKit"

end

target 'AppTorcedorNE10Tests' do

end

